import Head from 'next/head';
import Image from 'next/image';
import HeroBanner from '../components/utils/HeroBanner';
import Services from '../components/utils/Services';
import { BsFillTelephoneFill } from 'react-icons/bs';
import Team from '../components/utils/Team';
import MainContent from '../components/MainContent';
export default function Home() {
	return (
		<div>
			<Head>
				<link rel='icon' href='/favicon.ico' />
				<link rel='manifest' href='/manifest.json' />
				<link rel='apple-touch-icon' href='/vercel.svg' />

				<title>Terrance Brown Assessment</title>
				<meta name='description' content='Generated by create next app.' />
				<meta property='og:url' content='' />
				<meta property='og:type' content='website' />
				<meta property='og:title' content='' />
				<meta
					property='og:description'
					content='Generated by create next app.'
				/>
				<meta property='og:image' content='' />

				<meta name='twitter:card' content='summary_large_image' />
				<meta property='twitter:domain' content='' />
				<meta property='twitter:url' content='' />
				<meta name='twitter:title' content='' />
				<meta
					name='twitter:description'
					content='Generated by create next app.'
				/>
				<meta name='twitter:image' content='' />
			</Head>

			<HeroBanner>
				<div className='flex min-h-full flex-col items-center justify-center'>
					<h2 className='lg:9xl text-center text-3xl font-semibold md:text-7xl'>
						{' '}
						Wizards Basketball
					</h2>
					<p className='mt-8 w-8/12 text-center text-sm tracking-tight md:text-lg  lg:text-2xl'>
						Simple Statistics Site. Mobile First Design
					</p>
				</div>
			</HeroBanner>

			<Team />
		</div>
	);
}
